import React, { useState } from "react";
import Header from "./Header";
import Footer from "./Footer";
import { useRouter } from "next/router";
import Head from "next/head";

export default function Layout({ children }: { children: React.ReactNode }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>next-note</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="flex flex-col h-full justify-between bg-slate-100">
        {router.pathname !== "/404" && <Header />}
        <main className="my-5 h-full min-h-screen">{children}</main>
        {router.pathname !== "/404" && <Footer />}
      </div>
    </>
  );
}
